
analyzer:
  errors:
    unintended_html_in_doc_comment: ignore
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - await_only_futures
    - unawaited_futures


# analyzer:
###   exclude:
###     - path/to/excluded/files/**